name: gha custom action docker demo
description: demo gha docker container action
author: puglao

inputs:
  echoMessage:
    description: 'Message to print in container'
    required: false
    default: "World"
    
outputs:
  runHex:
    description: 'random hex to output'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'upload-cloud'
  color: 'white'